"""Property-based tests for safety filtering.

Feature: sikshya-sathi-system
Property 16: Safety Content Filtering

For any content generated by the Cloud Brain, if unsafe or inappropriate
material is detected, the content must be rejected and regenerated until
it passes safety filters.

Validates: Requirements 7.1, 7.4
"""

import pytest
from hypothesis import given, strategies as st, settings, HealthCheck

from src.models.validation import ValidationCheckType, ValidationStatus
from src.services.safety_filter import SafetyFilter


# Custom strategies for generating test data
@st.composite
def safe_content_strategy(draw):
    """Generate safe educational content that should pass safety filtering."""
    safe_topics = [
        "addition and subtraction",
        "multiplication tables",
        "basic geometry shapes",
        "plant biology",
        "water cycle",
        "solar system",
        "reading comprehension",
        "grammar rules",
        "Nepali culture and traditions",
        "historical events",
        "geography of Nepal",
    ]
    
    topic = draw(st.sampled_from(safe_topics))
    
    # Generate safe educational content - avoid words that might trigger false positives
    content_templates = [
        f"This lesson teaches {topic}. Students will learn fundamental concepts through examples and practice.",
        f"In this lesson, we explore {topic}. Students will understand key principles and apply them.",
        f"Learn about {topic} in this comprehensive lesson. Practice exercises are included.",
        f"This educational content covers {topic}. Students will gain knowledge through guided activities.",
        f"Students will study {topic} and master important concepts.",
        f"This lesson introduces {topic} with clear explanations and examples.",
    ]
    
    content = draw(st.sampled_from(content_templates))
    
    return content


@st.composite
def unsafe_content_strategy(draw):
    """Generate unsafe content that should be rejected by safety filters."""
    # Categories of unsafe content
    violence_content = [
        "This lesson teaches how to kill and attack enemies with weapons.",
        "Learn about violence and how to fight using guns and knives.",
        "Students will practice assault techniques and weapon handling.",
        "This content discusses murder and violent attacks.",
    ]
    
    adult_content = [
        "This lesson contains explicit adult content and sexual material.",
        "Learn about adult topics and sexual activities.",
        "This content includes pornographic material for students.",
        "Students will explore explicit adult themes.",
    ]
    
    substance_content = [
        "This lesson teaches how to use drugs and alcohol.",
        "Learn about cocaine, heroin, and marijuana usage.",
        "Students will practice drinking alcohol and smoking cigarettes.",
        "This content promotes drug use among teenagers.",
    ]
    
    gambling_content = [
        "Learn how to gamble at casinos and bet on poker games.",
        "This lesson teaches casino games and gambling strategies.",
        "Students will practice betting and lottery techniques.",
        "This content promotes gambling and casino activities.",
    ]
    
    hate_speech_content = [
        "This lesson promotes hate and discrimination against groups.",
        "Learn about racist ideologies and prejudice.",
        "This content encourages discrimination and hate speech.",
        "Students will explore prejudiced views and racist concepts.",
    ]
    
    all_unsafe = (
        violence_content
        + adult_content
        + substance_content
        + gambling_content
        + hate_speech_content
    )
    
    return draw(st.sampled_from(all_unsafe))


@st.composite
def culturally_sensitive_content_strategy(draw):
    """Generate culturally sensitive content for Nepal context that matches patterns."""
    # Use exact patterns from safety_filter.py to ensure they match
    political_content = [
        "This lesson discusses political party conflicts in Nepal.",
        "Learn about election controversies and government corruption.",
        "Students will explore political protests and revolution.",
    ]
    
    religious_content = [
        "This lesson discusses Hindu Muslim tensions in the region.",
        "Learn about Christian conversion efforts in Nepal.",
        "Students will explore religious conflict between communities.",
    ]
    
    caste_content = [
        "This lesson discusses the caste system in Nepal.",
        "Learn about untouchable discrimination and social hierarchy.",
        "Students will explore Brahmin superiority and caste hierarchy.",
    ]
    
    ethnic_content = [
        "This lesson discusses ethnic conflict in Nepal.",
        "Learn about Madhesi and Pahadi ethnic tensions.",
        "Students will explore ethnic superiority claims.",
    ]
    
    all_sensitive = (
        political_content
        + religious_content
        + caste_content
        + ethnic_content
    )
    
    return draw(st.sampled_from(all_sensitive))


@st.composite
def mixed_content_strategy(draw):
    """Generate content that may be safe or unsafe."""
    content_type = draw(st.sampled_from(["safe", "unsafe", "sensitive"]))
    
    if content_type == "safe":
        return draw(safe_content_strategy())
    elif content_type == "unsafe":
        return draw(unsafe_content_strategy())
    else:
        return draw(culturally_sensitive_content_strategy())


@pytest.fixture
def safety_filter():
    """Create a safety filter instance for testing."""
    return SafetyFilter(
        guardrail_id=None,  # Disable Bedrock Guardrails for property tests
        audit_table_name=None,  # Disable audit logging for property tests
    )


@pytest.mark.property_test
@settings(
    max_examples=100,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(content=safe_content_strategy())
def test_property_16_safe_content_passes_filtering(safety_filter, content):
    """Property 16: Safe content must pass safety filtering
    
    For any safe educational content, the safety filter must allow it to pass
    without rejection.
    
    This verifies that the safety filter does not incorrectly reject
    appropriate educational content.
    """
    # Filter the safe content
    result = safety_filter.filter_content(
        content=content,
        content_id=f"test-safe-{hash(content)}",
        content_type="lesson",
        use_guardrails=False,
    )
    
    # Property 16: Safe content must pass
    assert result.status == ValidationStatus.PASSED, \
        f"Safe content should pass filtering but got {result.status}: {result.issues}"
    
    # Property 16: No safety filter failures for safe content
    assert ValidationCheckType.SAFETY_FILTER not in result.failed_checks, \
        "Safe content should not fail safety filter check"
    
    # Property 16: No critical issues for safe content
    critical_issues = [i for i in result.issues if i.severity == "critical"]
    assert len(critical_issues) == 0, \
        f"Safe content should not have critical issues: {critical_issues}"


@pytest.mark.property_test
@settings(
    max_examples=100,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(content=unsafe_content_strategy())
def test_property_16_unsafe_content_rejected(safety_filter, content):
    """Property 16: Unsafe content must be rejected
    
    For any content containing unsafe or inappropriate material, the safety
    filter must detect it and reject the content.
    
    This is the core property: unsafe content MUST be rejected.
    """
    # Filter the unsafe content
    result = safety_filter.filter_content(
        content=content,
        content_id=f"test-unsafe-{hash(content)}",
        content_type="lesson",
        use_guardrails=False,
    )
    
    # Property 16: Unsafe content must be rejected
    assert result.status in [ValidationStatus.FAILED, ValidationStatus.NEEDS_REGENERATION], \
        f"Unsafe content must be rejected but got {result.status}"
    
    # Property 16: Safety filter must fail for unsafe content
    assert ValidationCheckType.SAFETY_FILTER in result.failed_checks, \
        "Unsafe content must fail safety filter check"
    
    # Property 16: Must have documented issues
    assert len(result.issues) > 0, \
        "Rejected content must have documented issues"
    
    # Property 16: Must have at least one high or critical severity issue
    high_severity_issues = [
        i for i in result.issues
        if i.severity in ["high", "critical"]
    ]
    assert len(high_severity_issues) > 0, \
        "Unsafe content must have high or critical severity issues"


@pytest.mark.property_test
@settings(
    max_examples=100,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(content=culturally_sensitive_content_strategy())
def test_property_16_culturally_sensitive_content_flagged(safety_filter, content):
    """Property 16: Culturally sensitive content must be flagged
    
    For any content containing culturally sensitive material for Nepal context,
    the safety filter must detect and flag it appropriately.
    """
    # Filter the culturally sensitive content
    result = safety_filter.filter_content(
        content=content,
        content_id=f"test-sensitive-{hash(content)}",
        content_type="lesson",
        use_guardrails=False,
    )
    
    # Property 16: Culturally sensitive content must be flagged
    assert ValidationCheckType.CULTURAL_APPROPRIATENESS in result.failed_checks, \
        "Culturally sensitive content must fail cultural appropriateness check"
    
    # Property 16: Must have cultural appropriateness issues
    cultural_issues = [
        i for i in result.issues
        if i.check_type == ValidationCheckType.CULTURAL_APPROPRIATENESS
    ]
    assert len(cultural_issues) > 0, \
        "Culturally sensitive content must have documented cultural issues"
    
    # Property 16: Overall status must indicate rejection or need for regeneration
    assert result.status in [ValidationStatus.FAILED, ValidationStatus.NEEDS_REGENERATION], \
        "Culturally sensitive content must be rejected or flagged for regeneration"


@pytest.mark.property_test
@settings(
    max_examples=100,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(content=mixed_content_strategy())
def test_property_16_filtering_consistency(safety_filter, content):
    """Property 16: Safety filtering must be consistent
    
    For any content, filtering the same content multiple times must produce
    consistent results.
    """
    # Filter the content twice
    result1 = safety_filter.filter_content(
        content=content,
        content_id=f"test-consistency-1-{hash(content)}",
        content_type="lesson",
        use_guardrails=False,
    )
    
    result2 = safety_filter.filter_content(
        content=content,
        content_id=f"test-consistency-2-{hash(content)}",
        content_type="lesson",
        use_guardrails=False,
    )
    
    # Property 16: Same content must produce same validation status
    assert result1.status == result2.status, \
        "Same content must produce consistent validation status"
    
    # Property 16: Same content must have same passed checks
    assert set(result1.passed_checks) == set(result2.passed_checks), \
        "Same content must pass same checks consistently"
    
    # Property 16: Same content must have same failed checks
    assert set(result1.failed_checks) == set(result2.failed_checks), \
        "Same content must fail same checks consistently"


@pytest.mark.property_test
@settings(
    max_examples=50,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(
    content=unsafe_content_strategy(),
    content_type=st.sampled_from(["lesson", "quiz", "hint"])
)
def test_property_16_rejection_across_content_types(safety_filter, content, content_type):
    """Property 16: Unsafe content must be rejected regardless of content type
    
    For any unsafe content, it must be rejected whether it's a lesson, quiz,
    or hint.
    """
    # Filter the unsafe content
    result = safety_filter.filter_content(
        content=content,
        content_id=f"test-type-{content_type}-{hash(content)}",
        content_type=content_type,
        use_guardrails=False,
    )
    
    # Property 16: Unsafe content must be rejected for all content types
    assert result.status in [ValidationStatus.FAILED, ValidationStatus.NEEDS_REGENERATION], \
        f"Unsafe {content_type} must be rejected"
    
    # Property 16: Must fail safety filter check
    assert ValidationCheckType.SAFETY_FILTER in result.failed_checks, \
        f"Unsafe {content_type} must fail safety filter"


@pytest.mark.property_test
@settings(
    max_examples=50,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(content=unsafe_content_strategy())
def test_property_16_rejection_provides_actionable_feedback(safety_filter, content):
    """Property 16: Rejected content must provide actionable feedback
    
    For any rejected content, the safety filter must provide clear issues
    with severity levels and suggestions for correction.
    """
    # Filter the unsafe content
    result = safety_filter.filter_content(
        content=content,
        content_id=f"test-feedback-{hash(content)}",
        content_type="lesson",
        use_guardrails=False,
    )
    
    # Property 16: Rejected content must have issues
    assert len(result.issues) > 0, \
        "Rejected content must have documented issues"
    
    # Property 16: Each issue must have required fields
    for issue in result.issues:
        assert issue.check_type is not None, \
            "Issue must have check type"
        assert issue.severity in ["low", "medium", "high", "critical"], \
            f"Issue must have valid severity, got {issue.severity}"
        assert issue.message, \
            "Issue must have a message"
        assert issue.suggestion, \
            "Issue must have a suggestion for correction"
    
    # Property 16: At least one issue must be from safety filter
    safety_issues = [
        i for i in result.issues
        if i.check_type in [
            ValidationCheckType.SAFETY_FILTER,
            ValidationCheckType.CULTURAL_APPROPRIATENESS
        ]
    ]
    assert len(safety_issues) > 0, \
        "Rejected content must have safety-related issues"


@pytest.mark.property_test
@settings(
    max_examples=50,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(
    safe_content=safe_content_strategy(),
    unsafe_content=unsafe_content_strategy()
)
def test_property_16_differential_filtering(safety_filter, safe_content, unsafe_content):
    """Property 16: Safety filter must differentiate between safe and unsafe content
    
    For any pair of safe and unsafe content, the safety filter must correctly
    identify and handle them differently.
    """
    # Filter safe content
    safe_result = safety_filter.filter_content(
        content=safe_content,
        content_id=f"test-diff-safe-{hash(safe_content)}",
        content_type="lesson",
        use_guardrails=False,
    )
    
    # Filter unsafe content
    unsafe_result = safety_filter.filter_content(
        content=unsafe_content,
        content_id=f"test-diff-unsafe-{hash(unsafe_content)}",
        content_type="lesson",
        use_guardrails=False,
    )
    
    # Property 16: Safe content must pass
    assert safe_result.status == ValidationStatus.PASSED, \
        "Safe content must pass filtering"
    
    # Property 16: Unsafe content must be rejected
    assert unsafe_result.status in [ValidationStatus.FAILED, ValidationStatus.NEEDS_REGENERATION], \
        "Unsafe content must be rejected"
    
    # Property 16: Unsafe content must have more issues than safe content
    assert len(unsafe_result.issues) > len(safe_result.issues), \
        "Unsafe content must have more issues than safe content"
    
    # Property 16: Unsafe content must have safety filter failures
    assert ValidationCheckType.SAFETY_FILTER in unsafe_result.failed_checks, \
        "Unsafe content must fail safety filter check"
    
    # Property 16: Safe content must not have safety filter failures
    assert ValidationCheckType.SAFETY_FILTER not in safe_result.failed_checks, \
        "Safe content must not fail safety filter check"


@pytest.mark.property_test
@settings(
    max_examples=30,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(content=st.text(min_size=0, max_size=1000))
def test_property_16_handles_arbitrary_content(safety_filter, content):
    """Property 16: Safety filter must handle arbitrary content gracefully
    
    For any arbitrary text content, the safety filter must process it without
    errors and return a valid result.
    """
    # Filter arbitrary content
    result = safety_filter.filter_content(
        content=content,
        content_id=f"test-arbitrary-{hash(content)}",
        content_type="lesson",
        use_guardrails=False,
    )
    
    # Property 16: Must return a valid result
    assert result is not None, \
        "Safety filter must return a result"
    
    # Property 16: Must have a valid status
    assert result.status in [
        ValidationStatus.PASSED,
        ValidationStatus.FAILED,
        ValidationStatus.NEEDS_REGENERATION
    ], \
        "Result must have a valid status"
    
    # Property 16: Must have performed safety checks
    all_checks = result.passed_checks + result.failed_checks
    assert ValidationCheckType.SAFETY_FILTER in all_checks, \
        "Safety filter check must be performed"
    assert ValidationCheckType.CULTURAL_APPROPRIATENESS in all_checks, \
        "Cultural appropriateness check must be performed"
    
    # Property 16: If failed, must have issues
    if result.status in [ValidationStatus.FAILED, ValidationStatus.NEEDS_REGENERATION]:
        assert len(result.issues) > 0, \
            "Failed validation must have documented issues"
