"""Property-based tests for content validation.

Feature: sikshya-sathi-system
Property 1: Content Curriculum Alignment

For any content generated by the Cloud Brain (lessons, quizzes, hints),
the content must be validated by the Curriculum Validator and map to
specific Nepal K-12 curriculum standards before being included in a
Learning Bundle.

Validates: Requirements 2.2, 2.10, 6.1, 6.2
"""

import pytest
from hypothesis import given, strategies as st, settings, HealthCheck

from src.models.curriculum import Subject
from src.models.validation import (
    ContentValidationRequest,
    ValidationCheckType,
    ValidationStatus,
)
from src.services.content_validator import ContentValidator


# Custom strategies for generating test data
@st.composite
def valid_content_strategy(draw):
    """Generate valid educational content that should pass validation."""
    subjects = [
        Subject.MATHEMATICS.value,
        Subject.SCIENCE.value,
        Subject.ENGLISH.value,
        Subject.NEPALI.value,
        Subject.SOCIAL_STUDIES.value,
    ]
    
    subject = draw(st.sampled_from(subjects))
    grade = draw(st.integers(min_value=6, max_value=8))
    
    # Generate content appropriate for the subject
    if subject == Subject.MATHEMATICS.value:
        content = draw(st.text(
            alphabet=st.characters(whitelist_categories=('Lu', 'Ll', 'Nd', 'Zs', 'Po')),
            min_size=50,
            max_size=500
        ))
        # Ensure it has mathematical context
        content = f"This lesson teaches addition and subtraction. {content} Students will practice with numbers."
        target_standards = [f"MATH-{grade}-001"]
    elif subject == Subject.SCIENCE.value:
        content = draw(st.text(
            alphabet=st.characters(whitelist_categories=('Lu', 'Ll', 'Nd', 'Zs', 'Po')),
            min_size=50,
            max_size=500
        ))
        content = f"This lesson covers basic science concepts. {content} Students will learn through observation."
        target_standards = [f"SCIENCE-{grade}-001"]
    else:
        content = draw(st.text(
            alphabet=st.characters(whitelist_categories=('Lu', 'Ll', 'Nd', 'Zs', 'Po')),
            min_size=50,
            max_size=500
        ))
        content = f"This lesson introduces language concepts. {content} Students will practice reading."
        target_standards = [f"{subject.upper()}-{grade}-001"]
    
    return ContentValidationRequest(
        content_id=draw(st.text(alphabet=st.characters(whitelist_categories=('Lu', 'Ll', 'Nd')), min_size=5, max_size=20)),
        content_type=draw(st.sampled_from(["lesson", "quiz", "hint"])),
        content=content,
        target_standards=target_standards,
        grade=grade,
        subject=subject,
    )


@st.composite
def invalid_content_strategy(draw):
    """Generate invalid educational content that should fail validation."""
    subjects = [
        Subject.MATHEMATICS.value,
        Subject.SCIENCE.value,
        Subject.ENGLISH.value,
    ]
    
    subject = draw(st.sampled_from(subjects))
    grade = draw(st.integers(min_value=6, max_value=8))
    
    # Generate content with validation issues
    invalid_patterns = [
        "This lesson teaches violence and weapons.",
        "Learn how to make harmful substances.",
        "This content discusses adult topics.",
        "Provide your phone number and email address.",
    ]
    
    content = draw(st.sampled_from(invalid_patterns))
    target_standards = [f"{subject.upper()}-{grade}-001"]
    
    return ContentValidationRequest(
        content_id=draw(st.text(alphabet=st.characters(whitelist_categories=('Lu', 'Ll', 'Nd')), min_size=5, max_size=20)),
        content_type=draw(st.sampled_from(["lesson", "quiz", "hint"])),
        content=content,
        target_standards=target_standards,
        grade=grade,
        subject=subject,
    )


@pytest.fixture
def content_validator():
    """Create a content validator instance for testing."""
    return ContentValidator(
        alignment_threshold=0.7,
        max_regeneration_attempts=3,
        guardrail_id=None,  # Disable Bedrock Guardrails for tests
        audit_table_name=None,  # Disable audit logging for tests
    )


@pytest.mark.property_test
@settings(
    max_examples=100,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(request=valid_content_strategy())
def test_property_1_all_content_must_be_validated(content_validator, request):
    """Property 1: Content Curriculum Alignment
    
    For any content generated by the Cloud Brain, the content must be
    validated by the Curriculum Validator and map to specific Nepal K-12
    curriculum standards.
    
    This property verifies that:
    1. All content goes through validation pipeline
    2. Validation checks curriculum alignment
    3. Content is mapped to curriculum standards
    4. Validation result includes alignment information
    """
    # Validate the content
    result = content_validator.validate_content(request, use_guardrails=False)
    
    # Property 1: Content must be validated
    assert result is not None, "Validation must return a result"
    assert result.content_id == request.content_id, "Result must match request"
    assert result.content_type == request.content_type, "Content type must be preserved"
    
    # Property 1: Validation must check curriculum alignment
    assert (
        ValidationCheckType.CURRICULUM_ALIGNMENT in result.passed_checks
        or ValidationCheckType.CURRICULUM_ALIGNMENT in result.failed_checks
    ), "Curriculum alignment check must be performed"
    
    # Property 1: Result must include alignment score (if alignment check succeeded)
    # Note: alignment_score may be None if MCP server is unavailable or errors occur
    if result.alignment_score is not None:
        assert 0.0 <= result.alignment_score <= 1.0, "Alignment score must be between 0 and 1"
    
    # Property 1: Content must have a definitive validation status
    assert result.status in [
        ValidationStatus.PASSED,
        ValidationStatus.FAILED,
        ValidationStatus.NEEDS_REGENERATION,
    ], "Validation must return a valid status"


@pytest.mark.property_test
@settings(
    max_examples=100,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(request=valid_content_strategy())
def test_property_1_curriculum_standards_mapping(content_validator, request):
    """Property 1: Content must map to specific curriculum standards
    
    This property verifies that validation checks content against the
    target curriculum standards specified in the request.
    """
    # Validate the content
    result = content_validator.validate_content(request, use_guardrails=False)
    
    # Property 1: Validation must reference target standards
    # The curriculum validator should have checked alignment with target_standards
    assert request.target_standards is not None, "Request must have target standards"
    assert len(request.target_standards) > 0, "Request must specify at least one standard"
    
    # Property 1: If curriculum alignment check was performed, it used the standards
    if ValidationCheckType.CURRICULUM_ALIGNMENT in result.passed_checks:
        # Content passed curriculum alignment, meaning it was checked against standards
        assert result.alignment_score >= content_validator.curriculum_validator.alignment_threshold
    elif ValidationCheckType.CURRICULUM_ALIGNMENT in result.failed_checks:
        # Content failed curriculum alignment, but check was still performed
        alignment_issues = [
            issue for issue in result.issues
            if issue.check_type == ValidationCheckType.CURRICULUM_ALIGNMENT
        ]
        assert len(alignment_issues) > 0, "Failed alignment must have issues documented"


@pytest.mark.property_test
@settings(
    max_examples=100,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(request=invalid_content_strategy())
def test_property_1_invalid_content_rejected(content_validator, request):
    """Property 1: Invalid content must be rejected or flagged for regeneration
    
    This property verifies that content with validation issues is properly
    identified and not allowed to pass without correction.
    """
    # Validate the content
    result = content_validator.validate_content(request, use_guardrails=False)
    
    # Property 1: Invalid content must not pass validation
    assert result.status in [
        ValidationStatus.FAILED,
        ValidationStatus.NEEDS_REGENERATION,
    ], "Invalid content must be rejected or flagged for regeneration"
    
    # Property 1: Failed validation must document issues
    assert len(result.issues) > 0, "Failed validation must have documented issues"
    assert len(result.failed_checks) > 0, "Failed validation must have failed checks"
    
    # Property 1: Issues must have severity and suggestions
    for issue in result.issues:
        assert issue.severity in ["low", "medium", "high", "critical"], \
            "Issue must have valid severity"
        assert issue.message, "Issue must have a message"
        assert issue.suggestion, "Issue must have a suggestion for correction"


@pytest.mark.property_test
@settings(
    max_examples=50,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(request=valid_content_strategy())
def test_property_1_validation_pipeline_completeness(content_validator, request):
    """Property 1: All validation checks must be performed
    
    This property verifies that the complete validation pipeline is executed,
    including curriculum alignment, age-appropriateness, language, safety,
    and cultural appropriateness checks.
    """
    # Validate the content
    result = content_validator.validate_content(request, use_guardrails=False)
    
    # Property 1: All required validation checks must be performed
    all_checks = result.passed_checks + result.failed_checks
    
    # Must include curriculum alignment check
    assert ValidationCheckType.CURRICULUM_ALIGNMENT in all_checks, \
        "Curriculum alignment check must be performed"
    
    # Must include age appropriateness check
    assert ValidationCheckType.AGE_APPROPRIATENESS in all_checks, \
        "Age appropriateness check must be performed"
    
    # Must include language appropriateness check
    assert ValidationCheckType.LANGUAGE_APPROPRIATENESS in all_checks, \
        "Language appropriateness check must be performed"
    
    # Must include safety filter check
    assert ValidationCheckType.SAFETY_FILTER in all_checks, \
        "Safety filter check must be performed"
    
    # Must include cultural appropriateness check
    assert ValidationCheckType.CULTURAL_APPROPRIATENESS in all_checks, \
        "Cultural appropriateness check must be performed"
    
    # Property 1: No duplicate checks
    assert len(all_checks) == len(set(all_checks)), \
        "Validation checks must not be duplicated"


@pytest.mark.property_test
@settings(
    max_examples=50,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(
    request=valid_content_strategy(),
    regeneration_attempts=st.integers(min_value=0, max_value=3)
)
def test_property_1_regeneration_workflow(content_validator, request, regeneration_attempts):
    """Property 1: Content regeneration workflow maintains validation integrity
    
    This property verifies that when content fails validation and is
    regenerated, the validation process is repeated and maintains the same
    standards.
    """
    regeneration_count = 0
    
    def mock_regeneration(req, issues):
        nonlocal regeneration_count
        regeneration_count += 1
        
        # Simulate regeneration by returning slightly modified content
        return f"Regenerated content (attempt {regeneration_count}): {req.content}"
    
    # Validate with regeneration
    result, attempts = content_validator.validate_with_regeneration(
        request,
        mock_regeneration,
        use_guardrails=False,
    )
    
    # Property 1: Regeneration must respect max attempts
    assert attempts <= content_validator.max_regeneration_attempts, \
        "Regeneration must not exceed max attempts"
    
    # Property 1: Final result must have validation status
    assert result.status in [
        ValidationStatus.PASSED,
        ValidationStatus.FAILED,
        ValidationStatus.NEEDS_REGENERATION,
    ], "Final result must have valid status"
    
    # Property 1: If passed, all critical checks must pass
    if result.status == ValidationStatus.PASSED:
        critical_issues = [i for i in result.issues if i.severity == "critical"]
        assert len(critical_issues) == 0, \
            "Passed content must not have critical issues"


@pytest.mark.property_test
@settings(
    max_examples=50,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow]
)
@given(
    content_type=st.sampled_from(["lesson", "quiz", "hint"]),
    grade=st.integers(min_value=6, max_value=8),
    subject=st.sampled_from([s.value for s in Subject])
)
def test_property_1_validation_consistency(content_validator, content_type, grade, subject):
    """Property 1: Validation is consistent across content types
    
    This property verifies that validation standards are applied consistently
    regardless of content type (lesson, quiz, hint).
    """
    # Create two similar requests with same content but different IDs
    content = "This is a simple educational lesson about basic concepts. Students will learn fundamental ideas."
    
    request1 = ContentValidationRequest(
        content_id="test-001",
        content_type=content_type,
        content=content,
        target_standards=[f"{subject.upper()}-{grade}-001"],
        grade=grade,
        subject=subject,
    )
    
    request2 = ContentValidationRequest(
        content_id="test-002",
        content_type=content_type,
        content=content,
        target_standards=[f"{subject.upper()}-{grade}-001"],
        grade=grade,
        subject=subject,
    )
    
    # Validate both
    result1 = content_validator.validate_content(request1, use_guardrails=False)
    result2 = content_validator.validate_content(request2, use_guardrails=False)
    
    # Property 1: Same content should produce same validation outcome
    assert result1.status == result2.status, \
        "Same content should produce same validation status"
    
    assert set(result1.passed_checks) == set(result2.passed_checks), \
        "Same content should pass same checks"
    
    assert set(result1.failed_checks) == set(result2.failed_checks), \
        "Same content should fail same checks"
    
    # Alignment scores should be similar (allowing for minor variations)
    if result1.alignment_score is not None and result2.alignment_score is not None:
        assert abs(result1.alignment_score - result2.alignment_score) < 0.1, \
            "Same content should produce similar alignment scores"
