import { DashboardData } from './types';

export const mockDashboardData: DashboardData = {
  educator_id: 'EDU001',
  class_ids: ['CLASS001'],
  student_progress: [
    {
      student_id: 'S001',
      student_name: 'Aisha Sharma',
      subject: 'Mathematics',
      lessons_completed: 15,
      quizzes_completed: 10,
      average_accuracy: 0.855,
      total_time_spent: 3600,
      current_streak: 5,
      topics_in_progress: ['Algebra'],
      topics_mastered: ['Basic Arithmetic', 'Geometry'],
      last_active: '2024-02-20T10:30:00Z',
    },
    {
      student_id: 'S002',
      student_name: 'Bikram Thapa',
      subject: 'Mathematics',
      lessons_completed: 12,
      quizzes_completed: 8,
      average_accuracy: 0.72,
      total_time_spent: 2800,
      current_streak: 3,
      topics_in_progress: ['Fractions', 'Decimals'],
      topics_mastered: ['Basic Arithmetic'],
      last_active: '2024-02-21T14:15:00Z',
    },
    {
      student_id: 'S003',
      student_name: 'Chandani Rai',
      subject: 'Science',
      lessons_completed: 18,
      quizzes_completed: 12,
      average_accuracy: 0.91,
      total_time_spent: 4200,
      current_streak: 7,
      topics_in_progress: ['Physics'],
      topics_mastered: ['Biology', 'Chemistry Basics'],
      last_active: '2024-02-22T09:00:00Z',
    },
    {
      student_id: 'S004',
      student_name: 'Deepak Gurung',
      subject: 'Mathematics',
      lessons_completed: 8,
      quizzes_completed: 5,
      average_accuracy: 0.58,
      total_time_spent: 1800,
      current_streak: 2,
      topics_in_progress: ['Basic Arithmetic'],
      topics_mastered: [],
      last_active: '2024-02-19T16:45:00Z',
    },
    {
      student_id: 'S005',
      student_name: 'Elina Tamang',
      subject: 'English',
      lessons_completed: 20,
      quizzes_completed: 15,
      average_accuracy: 0.88,
      total_time_spent: 5000,
      current_streak: 10,
      topics_in_progress: ['Grammar'],
      topics_mastered: ['Vocabulary', 'Reading Comprehension'],
      last_active: '2024-02-22T11:20:00Z',
    },
  ],
  class_reports: [
    {
      class_id: 'CLASS001',
      class_name: 'Grade 5A',
      subject: 'Mathematics',
      total_students: 25,
      active_students: 20,
      average_completion_rate: 0.68,
      average_accuracy: 0.75,
      struggling_students: ['S004', 'S008', 'S012'],
      top_performers: ['S001', 'S003', 'S005'],
    },
  ],
  coverage_reports: [
    {
      class_id: 'CLASS001',
      subject: 'Mathematics',
      total_topics: 20,
      topics_covered: 15,
      topics_mastered: 10,
      coverage_percentage: 75,
      topic_details: [
        {
          topic_id: 'MATH001',
          covered: true,
          mastered: true,
          proficiency: 0.9,
        },
        {
          topic_id: 'MATH002',
          covered: true,
          mastered: false,
          proficiency: 0.65,
        },
      ],
    },
    {
      class_id: 'CLASS001',
      subject: 'Science',
      total_topics: 18,
      topics_covered: 12,
      topics_mastered: 8,
      coverage_percentage: 67,
      topic_details: [
        {
          topic_id: 'SCI001',
          covered: true,
          mastered: true,
          proficiency: 0.85,
        },
      ],
    },
    {
      class_id: 'CLASS001',
      subject: 'English',
      total_topics: 15,
      topics_covered: 13,
      topics_mastered: 11,
      coverage_percentage: 87,
      topic_details: [
        {
          topic_id: 'ENG001',
          covered: true,
          mastered: true,
          proficiency: 0.92,
        },
      ],
    },
  ],
};
